// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt6bJzM6cEVm4oMjqP4wo3e-RTjJks2nU',
    appId: '1:706908770844:web:2e92201b04c9027002c5d9',
    messagingSenderId: '706908770844',
    projectId: 'auth-58aa3',
    authDomain: 'auth-58aa3.firebaseapp.com',
    storageBucket: 'auth-58aa3.appspot.com',
    measurementId: 'G-CW359ZRQ8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOhQOACCVkESEIZ82UUg6XbJdZ0ckIvdw',
    appId: '1:706908770844:android:72c0bc6b4619d4bf02c5d9',
    messagingSenderId: '706908770844',
    projectId: 'auth-58aa3',
    storageBucket: 'auth-58aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkF62rQi4GmA_zflQbGRomy96iG1bOjPk',
    appId: '1:706908770844:ios:465732f1dfaf364402c5d9',
    messagingSenderId: '706908770844',
    projectId: 'auth-58aa3',
    storageBucket: 'auth-58aa3.appspot.com',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkF62rQi4GmA_zflQbGRomy96iG1bOjPk',
    appId: '1:706908770844:ios:465732f1dfaf364402c5d9',
    messagingSenderId: '706908770844',
    projectId: 'auth-58aa3',
    storageBucket: 'auth-58aa3.appspot.com',
    iosBundleId: 'com.example.loginRegistrationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt6bJzM6cEVm4oMjqP4wo3e-RTjJks2nU',
    appId: '1:706908770844:web:e687d28eef41749102c5d9',
    messagingSenderId: '706908770844',
    projectId: 'auth-58aa3',
    authDomain: 'auth-58aa3.firebaseapp.com',
    storageBucket: 'auth-58aa3.appspot.com',
    measurementId: 'G-RRHDT2HZ45',
  );
}
